### PR TITLE
fix: combine connector init and updateOpenOn JS executions

### LINKED ISSUE #108: Set open on click in vaadin 14.0.8
Client type error occurred when contextMenu.setOpenOnClick(true); after upgrading vaadin version to 14.0.8

Screen Shot 2019-10-08 at 15 49 56

### PR DESCRIPTION
**Pull request by pekam**
ensuring correct execution order of scripts

fix #108

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/109)

### CODE REVIEW

**Review by tomivirkki — APPROVED** [review]

File: vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuDemoIT.java [hunk 1]
```diff
@@ -70,6 +70,7 @@ public void openAndCloseContextMenuWithComponents_contentIsRendered() {
         Assert.assertEquals("This is not a menu item", label.getText());
 
         checkbox.click();
+        $("body").first().click();
```
Comment (pekam) [inline vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuDemoIT.java:73]: Fixing a flaky test. It has been unstable also in snapshot builds (master).

It passed consistently when running locally.

**Review by tomivirkki — APPROVED** [review]
